stages:
  Getting_data:
    cmd: python import_data.py
    deps:
    - import_data.py
    outs:
    - rawdata_new.csv
  Process_data:
    cmd: python get_data.py
    deps:
    - get_data.py
    - rawdata_new.csv
    outs:
    - data_processed.csv
  Train_data:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false
